const API_BASE_URL_DEVELOPMENT = "https://localhost:7165";
const API_BASE_URL_PRODUCTION = "https://aspnetcorereactpost-server.azurewebsites.net";

const ENDPOINT = {
  GET_ALL_POST: "get-all-posts",
  GET_POST_BY_ID: "get-post-by-id",
  CREATE_POST: "create-post",
  UPDATE_POST: "update-post",
  DELETE_POST_BY_ID: "delete-post-by-id",
};

const development = {
  API_URL_GET_ALL_POSTS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINT.GET_ALL_POST}`,
  API_URL_GET_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINT.GET_POST_BY_ID}`,
  API_URL_CREATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINT.CREATE_POST}`,
  API_URL_UPDATE_POST: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINT.UPDATE_POST}`,
  API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINT.DELETE_POST_BY_ID}`,
};

const production = {
  API_URL_GET_ALL_POSTS: `${API_BASE_URL_PRODUCTION}/${ENDPOINT.GET_ALL_POST}`,
  API_URL_GET_POST_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINT.GET_POST_BY_ID}`,
  API_URL_CREATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINT.CREATE_POST}`,
  API_URL_UPDATE_POST: `${API_BASE_URL_PRODUCTION}/${ENDPOINT.UPDATE_POST}`,
  API_URL_DELETE_POST_BY_ID: `${API_BASE_URL_PRODUCTION}/${ENDPOINT.DELETE_POST_BY_ID}`,
};

const Constants = process.env.NODE_ENV === "development" ? development : production;

export default Constants;
